### ISSUE TITLE
Use the new options element instead of text fields for multi-value settings

### ISSUE THREAD

**Issue by klonos** [backdrop-contrib/quicklink#9]
In Backdrop 1.12, we have implemented an `options` element, which improves the UX when entering multiple values (https://github.com/backdrop/backdrop-issues/issues/1005). We should use that instead of text fields.

One concern is backwards combatiility. We can require `dependencies[] = backdrop:system (>=1.12)` in the .info file of the module, but that means that we do not support previous versions of core. Is this OK?

**Comment by herbdool** [comment]
If you use a select field you get the new function automatically on newer BD versions. No need to declare dependencies.

I've only tried this with editing select fields. I suspect it doesn't work with the Form API.

**Comment by herbdool** [comment]
I'm going to close this since it's not possible.
